# Generated by Django 3.2 on 2024-10-26 21:06

import django.contrib.auth.validators
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241026_0022'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Обязательное поле. Не более 254 символов.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.models.validate_profile_endpoint_name], verbose_name='username'),
        ),
    ]
